stages:
  - test_all
variables:
  MYSQL_DATABASE: hello_flask_test
  MYSQL_ROOT_PASSWORD: newpass
  FLASK_ENV: testing

test_all:
  stage: test_all
    #  services:
           - name: mysql:5.6
           alias: mysql
  #    - name: redis:4
  #      alias: redis
  before_script:
    - pip install -U -r requirements/requirements.txt -i https://mirrors.aliyun.com/pypi/simple
    - pip install -U -r requirements/test_requirements.txt -i https://mirrors.aliyun.com/pypi/simple

  script:
    - flake8 app commands tests
    - python manage.py test