version: '3'
services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: newpass
       MYSQL_DATABASE: hello_flask

   hello_flask:
     depends_on:
       - db
     image: hello_flask:latest
     ports:
       - "5000:5000"
     restart: always
     environment:
        DB_HOST: db:3306

volumes:
    db_data: