"""add messages

Revision ID: 00c88cf1b1c6
Revises: b86d0c281208
Create Date: 2018-06-28 12:59:06.138829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "00c88cf1b1c6"
down_revision = "b86d0c281208"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "body")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("body", mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
