"""empty message

Revision ID: 091342041f5f
Revises: 888fece670ef
Create Date: 2018-08-12 11:45:06.527841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "091342041f5f"
down_revision = "888fece670ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "page_view",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=64), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("func_called", sa.String(length=64), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("referrer", sa.Text(), nullable=True),
        sa.Column("req_method", sa.SmallInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_page_view_timestamp"), "page_view", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_page_view_timestamp"), table_name="page_view")
    op.drop_table("page_view")
    # ### end Alembic commands ###
