"""empty message

Revision ID: 2f8c0b0e3661
Revises: 091342041f5f
Create Date: 2018-08-12 11:49:02.266393

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f8c0b0e3661'
down_revision = '091342041f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('page_view', 'req_method',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('page_view', 'req_method',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=True)
    # ### end Alembic commands ###
