"""empty message

Revision ID: 3f9f33e53cf6
Revises: 5b3cba63635d
Create Date: 2018-08-12 13:45:57.919516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f9f33e53cf6'
down_revision = '5b3cba63635d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_view', 'func_called')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_view', sa.Column('func_called', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
