"""empty message

Revision ID: 4ce1880c0531
Revises: ad569f3204d5
Create Date: 2018-08-12 14:31:57.167076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ce1880c0531'
down_revision = 'ad569f3204d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_ip', sa.String(length=16), nullable=False),
    sa.Column('last_visit', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_ip')
    )
    op.create_table('view_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('req_method', sa.String(length=64), nullable=False),
    sa.Column('end_point', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_view_message_end_point'), 'view_message', ['end_point'], unique=False)
    op.create_index(op.f('ix_view_message_timestamp'), 'view_message', ['timestamp'], unique=False)
    op.drop_index('ix_page_view_end_point', table_name='page_view')
    op.drop_index('ix_page_view_timestamp', table_name='page_view')
    op.drop_table('page_view')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_view',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('ip', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('referrer', mysql.TEXT(), nullable=True),
    sa.Column('req_method', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('end_point', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('user_agent', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_page_view_timestamp', 'page_view', ['timestamp'], unique=False)
    op.create_index('ix_page_view_end_point', 'page_view', ['end_point'], unique=False)
    op.drop_index(op.f('ix_view_message_timestamp'), table_name='view_message')
    op.drop_index(op.f('ix_view_message_end_point'), table_name='view_message')
    op.drop_table('view_message')
    op.drop_table('user_message')
    # ### end Alembic commands ###
