"""empty message

Revision ID: 5b3cba63635d
Revises: e569e3e6bdd0
Create Date: 2018-08-12 13:43:56.859309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5b3cba63635d"
down_revision = "e569e3e6bdd0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "page_view", sa.Column("end_point", sa.String(length=64), nullable=False)
    )
    op.create_index(
        op.f("ix_page_view_end_point"), "page_view", ["end_point"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_page_view_end_point"), table_name="page_view")
    op.drop_column("page_view", "end_point")
    # ### end Alembic commands ###
