"""add Message

Revision ID: 678bfe9642ee
Revises: 5e819dd9ba48
Create Date: 2018-06-28 01:06:39.139218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "678bfe9642ee"
down_revision = "5e819dd9ba48"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=True),
        sa.Column("recipient_id", sa.Integer(), nullable=True),
        sa.Column("body", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["recipient_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["sender_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_body"), "message", ["body"], unique=False)
    op.add_column(
        u"users", sa.Column("last_message_read_time", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u"users", "last_message_read_time")
    op.drop_index(op.f("ix_message_body"), table_name="message")
    op.drop_table("message")
    # ### end Alembic commands ###
