"""empty message

Revision ID: 713e86ee90e8
Revises: 2f8c0b0e3661
Create Date: 2018-08-12 11:51:00.259162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "713e86ee90e8"
down_revision = "2f8c0b0e3661"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("page_view", "req_method")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "page_view",
        sa.Column(
            "req_method",
            mysql.SMALLINT(display_width=6),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
