"""add notifations

Revision ID: 888fece670ef
Revises: f2ca054efdfc
Create Date: 2018-06-29 22:37:45.573883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "888fece670ef"
down_revision = "f2ca054efdfc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.Float(), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_name"), "notification", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_notification_timestamp"), "notification", ["timestamp"], unique=False
    )
    op.alter_column(
        u"users",
        "password_hash",
        existing_type=mysql.VARCHAR(length=128),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        u"users",
        "password_hash",
        existing_type=mysql.VARCHAR(length=128),
        nullable=True,
    )
    op.drop_index(op.f("ix_notification_timestamp"), table_name="notification")
    op.drop_index(op.f("ix_notification_name"), table_name="notification")
    op.drop_table("notification")
    # ### end Alembic commands ###
