"""empty message

Revision ID: 8ef39f3d7265
Revises: c2e792f67b3a
Create Date: 2018-10-05 10:32:49.838972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "8ef39f3d7265"
down_revision = "c2e792f67b3a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_track_ip_address", table_name="track")
    op.drop_table("track")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "track",
        sa.Column("id", mysql.INTEGER(display_width=11), nullable=False),
        sa.Column("ip_address", mysql.VARCHAR(length=15), nullable=True),
        sa.Column("visit_time", mysql.DATETIME(), nullable=True),
        sa.Column(
            "visit_Count",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_track_ip_address", "track", ["ip_address"], unique=True)
    # ### end Alembic commands ###
