"""empty message

Revision ID: ad569f3204d5
Revises: 3f9f33e53cf6
Create Date: 2018-08-12 13:47:49.205165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ad569f3204d5"
down_revision = "3f9f33e53cf6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "page_view", sa.Column("user_agent", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("page_view", "user_agent")
    # ### end Alembic commands ###
