"""add messages

Revision ID: b86d0c281208
Revises: 678bfe9642ee
Create Date: 2018-06-28 12:54:56.854216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b86d0c281208"
down_revision = "678bfe9642ee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("timestamp", sa.DateTime(), nullable=True))
    op.create_index(
        op.f("ix_message_timestamp"), "message", ["timestamp"], unique=False
    )
    op.drop_index("ix_message_body", table_name="message")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_message_body", "message", ["body"], unique=False)
    op.drop_index(op.f("ix_message_timestamp"), table_name="message")
    op.drop_column("message", "timestamp")
    # ### end Alembic commands ###
