"""empty message

Revision ID: bc7e98fd8ebf
Revises: 5bd2be4991b8
Create Date: 2018-06-25 19:07:06.970158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7e98fd8ebf'
down_revision = '5bd2be4991b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=True),
    sa.Column('visit_time', sa.DateTime(), nullable=True),
    sa.Column('visit_Count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_ip_address'), 'track', ['ip_address'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_ip_address'), table_name='track')
    op.drop_table('track')
    # ### end Alembic commands ###
