"""empty message

Revision ID: c2e792f67b3a
Revises: 4ce1880c0531
Create Date: 2018-08-12 14:33:19.961992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c2e792f67b3a"
down_revision = "4ce1880c0531"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("view_message", sa.Column("ip", sa.String(length=16), nullable=True))
    op.create_foreign_key(None, "view_message", "user_message", ["ip"], ["user_ip"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "view_message", type_="foreignkey")
    op.drop_column("view_message", "ip")
    # ### end Alembic commands ###
