"""empty message

Revision ID: c495118a9587
Revises: 7bd2dbb2fffd
Create Date: 2018-05-16 23:16:16.100904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c495118a9587"
down_revision = "7bd2dbb2fffd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("disabled", sa.Boolean(), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("post_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_comments_timestamp"), "comments", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comments_timestamp"), table_name="comments")
    op.drop_table("comments")
    # ### end Alembic commands ###
