"""add messages

Revision ID: f2ca054efdfc
Revises: 00c88cf1b1c6
Create Date: 2018-06-28 12:59:27.542301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ca054efdfc'
down_revision = '00c88cf1b1c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('body', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'body')
    # ### end Alembic commands ###
