"""empty message

Revision ID: f57f82e51587
Revises: 12a2dab70622
Create Date: 2018-05-14 16:11:57.331486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f57f82e51587"
down_revision = "12a2dab70622"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("body_html", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "body_html")
    # ### end Alembic commands ###
